### ISSUE TITLE
Split List view and Grid view demos

### ISSUE THREAD

**Issue by sonnyp** [workbenchdev/demos#121]
We have Column View which is a separate demo, no reason for List View and Grid View to be together.

Let's split the demo "List View Widgets" into "List View" and "Grid View"

**Comment by BharatAtbrat** [comment]
Screengrabs:

https://github.com/workbenchdev/demos/assets/72352158/e6e61d1f-2535-4871-9ff3-fb7b34ef78ea


https://github.com/workbenchdev/demos/assets/72352158/2501a863-c141-4094-b2e0-0303c645caa0

Do you think these look good?

Also, do we need to change the description for them? I changed the grammar but it's the same sentence for both
