### ISSUE TITLE
Add filter to FileDialog Lbrary entry

### ISSUE THREAD

**Issue by sonnyp** [workbenchdev/demos#4]
We should demonstrate the usage of filter in the Open File library entry

```
  text_files = gtk_file_filter_new ();
  gtk_file_filter_set_name (text_files, _("Text Files"));
  gtk_file_filter_add_mime_type (text_files, "text/plain");
  gtk_file_filter_add_mime_type (text_files, "application/x-zerosize");
  gtk_file_chooser_add_filter (GTK_FILE_CHOOSER (native), g_object_ref (text_files));

```

**Comment by Sahil-Shadwal** [comment]
Hey @sonnyp can you tell me the expected behavior of Open File cause it is showing error when i select open file 
![image](https://github.com/workbenchdev/demos/assets/119167601/e2817bd0-af5b-481b-9324-5d46c0c9690a)
and open multiple files just logs the number of file selected .

**Comment by Sahil-Shadwal** [comment]
okay but open file is supposed to open the selected image or file or just log it in console?
![image](https://github.com/workbenchdev/demos/assets/119167601/9888b344-3858-423a-936b-f7ad48313af9)
@sonnyp

**Comment by Sahil-Shadwal** [comment]
Removed initial_folder and default_folder. https://gist.github.com/Sahil-Shadwal/6d63af8c237bf069e4ed7af7026a5790

**Comment by Sahil-Shadwal** [comment]
So, should i make PR first and get my code reviewed or after ?

**Comment by Sahil-Shadwal** [comment]
hey do i need to add more filters ?
