### ISSUE TITLE
Adw.ViewSwitcherTitle is deprecated

### ISSUE THREAD

**Issue by sonnyp** [workbenchdev/demos#42]
In the View Switcher demo, we use a deprecated feature.

We should migrate following the guide:

https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/migrating-to-breakpoints.html#replace-adwviewswitchertitle

**Comment by Sahil-Shadwal** [comment]
can i work on this ?

**Comment by Sahil-Shadwal** [comment]
Had some doubts in PR can you please review them ?
