### ISSUE TITLE
List View Widgets demo errors with Vala

### ISSUE THREAD

**Issue by sonnyp** [workbenchdev/demos#43]
Added in https://github.com/workbenchdev/Workbench/pull/446

![image](https://github.com/workbenchdev/demos/assets/19673/d641a7d5-3237-4c5e-89c8-2c201d7659a4)

cc @lw64 @Diego-Ivan 

Might be worth looking at "List Model" as well.

**Comment by Diego-Ivan** [comment]
Just sent a PR to fix this. Took a look at the List Model demo and that one is working just as expected :)
