### ISSUE TITLE
Update window demo for libadwaita 1.5

### ISSUE THREAD

**Issue by sonnyp** [workbenchdev/demos#68]
See the first example here https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.Window.html

**Comment by Sahil-Shadwal** [comment]
By workbench env you mean, we have to access the window demo from workbench sub-module, right?

**Comment by Sahil-Shadwal** [comment]
![Screenshot from 2024-02-07 23-40-46](https://github.com/workbenchdev/demos/assets/119167601/9a59b694-65af-43ae-aaf5-3dc85a2574a6)
Will make PR soon.

**Comment by Siddhi0135** [comment]
@sonnyp is this issue still open? if yes , i would love to give it a try
